name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      - name: install
        run: npm run install
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      # - name: commitlint
      #   uses: wagoid/commitlint-github-action@v5.0.2
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [[ "$GITHUB_REF" = "refs/heads/master" ]]; then
            GITHUB_TOKEN=$GH_TOKEN npx semantic-release --verbose
          else
            echo "skipping release on branch $GITHUB_REF"
          fi
