name: main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: install
        run: yarn
      - name: build
        run: yarn build
      - name: test
        run: yarn test
      - name: commitlint
        uses: wagoid/commitlint-github-action@v2.2.0
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [[ "$GITHUB_REF" = "refs/heads/master" ]]; then
            GITHUB_TOKEN=$GH_TOKEN npx semantic-release --verbose
          else
            echo "skipping release on branch $GITHUB_REF"
          fi
